parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''
    api_version: 'v1'

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: 'Cinema Api'
    description: 'API Cinema (version avec API Platform v2)'
    version: 1.0.0

    enable_swagger_ui: false
    enable_re_doc: true

    collection:
        pagination:
            partial: true
            items_per_page_parameter_name: limit
            maximum_items_per_page: 1000
            client_items_per_page: true

    graphql:
        enabled: false
        graphiql:
            enabled: false

    formats:
        json:     ['application/json']
        html:     ['text/html']

    error_formats:
        jsonproblem:   ['application/problem+json']
